// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package main

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (ErrorResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ErrorResponse) UnmarshalJSON([]byte) error        { return nil }
func (ErrorResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ErrorResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ErrorResponse *ErrorResponse

func (Note) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Note) UnmarshalJSON([]byte) error        { return nil }
func (Note) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Note) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Note *Note

func (Notes) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Notes) UnmarshalJSON([]byte) error        { return nil }
func (Notes) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Notes) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Notes *Notes
